"""Per-site cookie jars for yt-dlp.

A jar is a live session for the site it belongs to, so nothing in this module
ever logs a cookie name or value — only counts and domains.

Layout: ``<storage_root>/cookies/<domain>.txt``, one Netscape-format jar per
site, plus a ``merged.txt`` regenerated on every write. yt-dlp takes a single
``cookiefile`` and only sends the cookies whose domain matches the request, so
merging is equivalent to handing it one browser profile rather than leaking
one site's session to another.
"""

import logging
import os
import re
from dataclasses import dataclass
from pathlib import Path

from app.config import settings

logger = logging.getLogger(__name__)

NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n"
MERGED_NAME = "merged.txt"

# A jar filename. Hostnames only: no separators, no traversal, no bare IPs
# (an IP would work as a filename but never as a cookie domain worth storing).
_DOMAIN_RE = re.compile(r"^(?!-)[a-z0-9-]{1,63}(?:\.(?!-)[a-z0-9-]{1,63})+$")
_IPV4_RE = re.compile(r"^\d{1,3}(?:\.\d{1,3}){3}$")

# Cookies that mean "this jar is actually signed in", per site. Absence is
# reported to the UI rather than rejected — a site we don't know about still
# gets stored, it just can't be checked.
SESSION_MARKERS: dict[str, tuple[str, ...]] = {
    "youtube.com": ("__Secure-3PSID", "LOGIN_INFO"),
    "google.com": ("__Secure-3PSID",),
}


def is_valid_domain(domain: str) -> bool:
    d = domain.strip().lower().lstrip(".")
    if not d or len(d) > 253 or ".." in d or "/" in d or "\\" in d:
        return False
    if _IPV4_RE.match(d) or ":" in d:
        return False
    return bool(_DOMAIN_RE.match(d))


def normalise_domain(domain: str) -> str:
    return domain.strip().lower().lstrip(".")


def cookies_dir() -> Path:
    """Resolve (and create, 0700) the jar directory."""
    d = settings.storage_root / "cookies"
    d.mkdir(parents=True, exist_ok=True)
    try:
        d.chmod(0o700)
    except OSError:  # pragma: no cover — non-POSIX or foreign owner
        pass
    return d


def jar_path(domain: str) -> Path:
    if not is_valid_domain(domain):
        raise ValueError(f"Invalid cookie domain: {domain!r}")
    return cookies_dir() / f"{normalise_domain(domain)}.txt"


# ---------------------------------------------------------------- serialising


def _line(c: dict) -> str | None:
    """One Netscape record, or None if the cookie is unusable."""
    name = str(c.get("name") or "")
    if not name or "\t" in name or "\n" in name:
        return None
    value = str(c.get("value") or "")
    if "\t" in value or "\n" in value:
        return None

    domain = normalise_domain(str(c.get("domain") or ""))
    if not domain:
        return None
    # A leading dot is how Netscape spells "and every subdomain". Firefox drops
    # the dot and reports host-only-ness separately, so reconstruct it.
    include_sub = bool(c.get("hostOnly")) is False
    domain_field = f".{domain}" if include_sub else domain

    path = str(c.get("path") or "/")
    secure = "TRUE" if c.get("secure") else "FALSE"

    # Session cookies are expiry 0 — MozillaCookieJar reads that as "discard".
    expiry = 0 if c.get("session") else int(c.get("expirationDate") or 0)

    prefix = "#HttpOnly_" if c.get("httpOnly") else ""
    return (
        f"{prefix}{domain_field}\t{'TRUE' if include_sub else 'FALSE'}\t{path}\t"
        f"{secure}\t{expiry}\t{name}\t{value}"
    )


def is_record(line: str) -> bool:
    """A cookie line. `#HttpOnly_` looks like a comment but is a record."""
    return bool(line.strip()) and (
        not line.startswith("#") or line.startswith("#HttpOnly_")
    )


def to_netscape(cookies: list[dict]) -> str:
    """Render browser.cookies.getAll() output as a Netscape cookie file."""
    lines = [NETSCAPE_HEADER, "# Generated by yt — do not edit.\n", "\n"]
    for c in cookies:
        rendered = _line(c)
        if rendered:
            lines.append(rendered + "\n")
    return "".join(lines)


# ------------------------------------------------------------------- writing


def _write_private(path: Path, text: str) -> None:
    """Write 0600, atomically, never widening the mode on an existing file."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise
    os.replace(tmp, path)


def rebuild_merged() -> Path | None:
    """Concatenate every jar into one file for yt-dlp. Returns it, or None."""
    d = cookies_dir()
    parts: list[str] = []
    for jar in sorted(d.glob("*.txt")):
        if jar.name == MERGED_NAME:
            continue
        try:
            body = jar.read_text(encoding="utf-8")
        except OSError as exc:
            logger.warning("Skipping unreadable cookie jar %s: %s", jar.name, exc)
            continue
        # Records only — each jar carries its own header and banner.
        parts.extend(ln for ln in body.splitlines(keepends=True) if is_record(ln))

    merged = d / MERGED_NAME
    if not parts:
        merged.unlink(missing_ok=True)
        return None
    _write_private(merged, NETSCAPE_HEADER + "".join(parts))
    return merged


def save_jar(domain: str, cookies: list[dict]) -> int:
    """Replace a site's jar. Returns the number of cookies actually written."""
    path = jar_path(domain)
    text = to_netscape(cookies)
    _write_private(path, text)
    rebuild_merged()
    written = sum(1 for ln in text.splitlines() if is_record(ln))
    logger.info("Stored %d cookie(s) for %s", written, normalise_domain(domain))
    return written


def delete_jar(domain: str) -> bool:
    path = jar_path(domain)
    existed = path.exists()
    path.unlink(missing_ok=True)
    rebuild_merged()
    if existed:
        logger.info("Deleted cookie jar for %s", normalise_domain(domain))
    return existed


# ------------------------------------------------------------------- reading


@dataclass
class JarStatus:
    domain: str
    cookie_count: int
    updated_at: float
    expires_at: int | None
    signed_in: bool | None


def _parse(path: Path) -> tuple[int, int | None, set[str]]:
    """Return (count, earliest non-session expiry, cookie names)."""
    count = 0
    soonest: int | None = None
    names: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        if not is_record(raw):
            continue
        line = raw.removeprefix("#HttpOnly_")
        fields = line.split("\t")
        if len(fields) < 7:
            continue
        count += 1
        names.add(fields[5])
        try:
            expiry = int(fields[4])
        except ValueError:
            continue
        if expiry > 0 and (soonest is None or expiry < soonest):
            soonest = expiry
    return count, soonest, names


def list_status() -> list[JarStatus]:
    """Per-site status, derived from the files. Never exposes values."""
    out: list[JarStatus] = []
    for jar in sorted(cookies_dir().glob("*.txt")):
        if jar.name == MERGED_NAME:
            continue
        domain = jar.stem
        try:
            count, expires, names = _parse(jar)
        except OSError as exc:
            logger.warning("Skipping unreadable cookie jar %s: %s", jar.name, exc)
            continue
        markers = SESSION_MARKERS.get(domain)
        out.append(
            JarStatus(
                domain=domain,
                cookie_count=count,
                updated_at=jar.stat().st_mtime,
                expires_at=expires,
                signed_in=all(m in names for m in markers) if markers else None,
            )
        )
    return out


def active_cookie_file() -> Path | None:
    """The cookiefile to hand yt-dlp.

    An explicit ``YT_COOKIES_FILE`` still wins, so a hand-managed jar keeps
    working; otherwise the merged jar the app maintains itself.
    """
    override = settings.yt_cookies_file
    if override and override.exists():
        return override
    merged = settings.storage_root / "cookies" / MERGED_NAME
    return merged if merged.exists() else None


# ------------------------------------------------------------- error mapping

# What yt-dlp says when a site wants an account. Its own advice ("use
# --cookies-from-browser") is useless here: there is no browser on the server,
# and the app has a page for exactly this.
_NEEDS_LOGIN_MARKERS = (
    "sign in to confirm your age",
    "confirm you're not a bot",
    "confirm you are not a bot",
    "this video is available to this channel's members",
    "join this channel to get access",
    "private video",
    "sign in to view",
    "login required",
    "requires authentication",
)


# Said when the jar *was* accepted and the account itself was refused. A
# different fix entirely: no amount of re-signing-in helps.
_ACCOUNT_REJECTED_MARKERS = (
    "sorry, this content is age-restricted",
    "content is age-restricted",
    "age-restricted video",
)


def explain_auth_error(message: str, url: str = "") -> str | None:
    """Rewrite a yt-dlp auth failure into something the user can act on.

    Returns None when the message is not about being signed out, so ordinary
    failures keep their original text.
    """
    lowered = message.lower()
    needs_login = any(marker in lowered for marker in _NEEDS_LOGIN_MARKERS)
    rejected = any(marker in lowered for marker in _ACCOUNT_REJECTED_MARKERS)
    if not needs_login and not rejected:
        return None

    if rejected:
        return (
            "The stored login was accepted, but YouTube would not serve this "
            "video to the server. If the same account can play it in your "
            "browser, the login is fine and the server is missing something the "
            "browser has — most often a working JavaScript runtime for yt-dlp's "
            "challenge solver. Check the backend logs for a challenge-solving "
            "warning before touching the login."
        )

    site = ""
    if url:
        from urllib.parse import urlparse

        host = (urlparse(url).hostname or "").removeprefix("www.")
        if host:
            site = f" to {host}"

    stored = {s.domain for s in list_status()}
    if not stored:
        return (
            f"This needs an account{site}. The archive is not signed in to any site "
            f"yet — add a login under Settings, then retry."
        )
    return (
        f"This needs an account{site}, and the stored login did not satisfy it. "
        f"The session may have expired, or the account may not be old enough or "
        f"a member. Refresh or replace the login under Settings, then retry. "
        f"(Signed in: {', '.join(sorted(stored))}.)"
    )
